version: "3"

services:
  eureka-server:
    image: bigsix_eureka_server
    ports:
    - 8761:8761

  auth-service:
    image: bigsix_auth_service
    ports:
    - 8762:8762

  league-service:
    image: bigsix_league_service
    ports:
    - 8763:8763

  prediction-service:
    image: bigsix_prediction_service
    ports:
    - 8764:8764